/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
export * from "./models";

// --- Centralized API client factory (hand-written, not generated) ---
export { initApiClient, getApiAxiosInstance, createApiConfiguration } from '../../api/api-client-factory';
export {
  getEstablishmentApi,
  getOrderApi,
  getPaymentApi,
  getProductApi,
  getTenantApi,
  getUploadApi,
  getUserApi,
  getWebhookApi,
  resetApiClients,
} from '../../api/clients';
