/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IOrderLine } from './iorder-line';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentMethod } from './payment-method';

/**
 * 
 * @export
 * @interface CreateOrderBody
 */
export interface CreateOrderBody {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderBody
     */
    'establishmentId': string;
    /**
     * 
     * @type {Array<IOrderLine>}
     * @memberof CreateOrderBody
     */
    'orderLines': Array<IOrderLine>;
    /**
     * 
     * @type {number}
     * @memberof CreateOrderBody
     */
    'total': number;
    /**
     * Construct a type with a set of properties K of type T
     * @type {{ [key: string]: any; }}
     * @memberof CreateOrderBody
     */
    'deliveryAddress'?: { [key: string]: any; };
    /**
     * Construct a type with a set of properties K of type T
     * @type {{ [key: string]: any; }}
     * @memberof CreateOrderBody
     */
    'billingInformation'?: { [key: string]: any; };
    /**
     * 
     * @type {PaymentMethod}
     * @memberof CreateOrderBody
     */
    'paymentMethod': PaymentMethod;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderBody
     */
    'deliveryMethod'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderBody
     */
    'remark'?: string;
}



