/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateTenantBodyContact } from './create-tenant-body-contact';
// May contain unused imports in some cases
// @ts-ignore
import { ITenantBranding } from './itenant-branding';

/**
 * 
 * @export
 * @interface CreateTenantBody
 */
export interface CreateTenantBody {
    /**
     * 
     * @type {string}
     * @memberof CreateTenantBody
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenantBody
     */
    'slug': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateTenantBody
     */
    'domains': Array<string>;
    /**
     * 
     * @type {ITenantBranding}
     * @memberof CreateTenantBody
     */
    'branding': ITenantBranding;
    /**
     * 
     * @type {CreateTenantBodyContact}
     * @memberof CreateTenantBody
     */
    'contact': CreateTenantBodyContact;
}

