/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateTenantBodyBranding
 */
export interface CreateTenantBodyBranding {
    /**
     * 
     * @type {string}
     * @memberof CreateTenantBodyBranding
     */
    'appName': string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenantBodyBranding
     */
    'primaryColor': string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenantBodyBranding
     */
    'logo': string;
}

