/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateOrderBodyOrderLinesInnerItem } from './create-order-body-order-lines-inner-item';

/**
 * 
 * @export
 * @interface CreateOrderBodyOrderLinesInner
 */
export interface CreateOrderBodyOrderLinesInner {
    /**
     * 
     * @type {CreateOrderBodyOrderLinesInnerItem}
     * @memberof CreateOrderBodyOrderLinesInner
     */
    'item': CreateOrderBodyOrderLinesInnerItem;
}

