/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetEstablishments200Response
 */
export interface GetEstablishments200Response {
    /**
     * 
     * @type {Array<any>}
     * @memberof GetEstablishments200Response
     */
    'establishments': Array<any>;
}

