/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IAnalyticsSummary } from './ianalytics-summary';
// May contain unused imports in some cases
// @ts-ignore
import { IMonthlyMetric } from './imonthly-metric';
// May contain unused imports in some cases
// @ts-ignore
import { IProductSales } from './iproduct-sales';

/**
 * 
 * @export
 * @interface IAnalyticsResponse
 */
export interface IAnalyticsResponse {
    /**
     * 
     * @type {IAnalyticsSummary}
     * @memberof IAnalyticsResponse
     */
    'summary': IAnalyticsSummary;
    /**
     * 
     * @type {Array<IMonthlyMetric>}
     * @memberof IAnalyticsResponse
     */
    'monthly': Array<IMonthlyMetric>;
    /**
     * 
     * @type {Array<IProductSales>}
     * @memberof IAnalyticsResponse
     */
    'bestSellers': Array<IProductSales>;
    /**
     * 
     * @type {Array<IProductSales>}
     * @memberof IAnalyticsResponse
     */
    'leastSellers': Array<IProductSales>;
}

