/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IDeliveryAddress
 */
export interface IDeliveryAddress {
    /**
     * 
     * @type {string}
     * @memberof IDeliveryAddress
     */
    'street'?: string;
    /**
     * 
     * @type {string}
     * @memberof IDeliveryAddress
     */
    'number'?: string;
    /**
     * 
     * @type {string}
     * @memberof IDeliveryAddress
     */
    'zipCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof IDeliveryAddress
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof IDeliveryAddress
     */
    'municipality'?: string;
    /**
     * 
     * @type {string}
     * @memberof IDeliveryAddress
     */
    'comment'?: string;
}

