/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EstablishmentStatus } from './establishment-status';

/**
 * 
 * @export
 * @interface IEstablishmentSummary
 */
export interface IEstablishmentSummary {
    /**
     * 
     * @type {string}
     * @memberof IEstablishmentSummary
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof IEstablishmentSummary
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof IEstablishmentSummary
     */
    'category': string;
    /**
     * 
     * @type {EstablishmentStatus}
     * @memberof IEstablishmentSummary
     */
    'status': EstablishmentStatus;
    /**
     * 
     * @type {string}
     * @memberof IEstablishmentSummary
     */
    'logo': string;
}



