/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IMonthlyMetric
 */
export interface IMonthlyMetric {
    /**
     * 
     * @type {number}
     * @memberof IMonthlyMetric
     */
    'month': number;
    /**
     * 
     * @type {number}
     * @memberof IMonthlyMetric
     */
    'orderCount': number;
    /**
     * 
     * @type {number}
     * @memberof IMonthlyMetric
     */
    'revenue': number;
}

