/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IOptionChoice } from './ioption-choice';
// May contain unused imports in some cases
// @ts-ignore
import { SelectionMode } from './selection-mode';

/**
 * 
 * @export
 * @interface IOptionGroup
 */
export interface IOptionGroup {
    /**
     * 
     * @type {string}
     * @memberof IOptionGroup
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof IOptionGroup
     */
    'required': boolean;
    /**
     * 
     * @type {SelectionMode}
     * @memberof IOptionGroup
     */
    'selectionMode': SelectionMode;
    /**
     * 
     * @type {number}
     * @memberof IOptionGroup
     */
    'maxSelections'?: number;
    /**
     * 
     * @type {Array<IOptionChoice>}
     * @memberof IOptionGroup
     */
    'choices': Array<IOptionChoice>;
}



