/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IOptionChoice
 */
export interface IOptionChoice {
    /**
     * 
     * @type {string}
     * @memberof IOptionChoice
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof IOptionChoice
     */
    'extraPrice': number;
    /**
     * 
     * @type {number}
     * @memberof IOptionChoice
     */
    'maxQuantity': number;
}

