/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EstablishmentStatus } from './establishment-status';
// May contain unused imports in some cases
// @ts-ignore
import { IAddress } from './iaddress';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentMethod } from './payment-method';

/**
 * 
 * @export
 * @interface IPublicEstablishment
 */
export interface IPublicEstablishment {
    /**
     * 
     * @type {string}
     * @memberof IPublicEstablishment
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof IPublicEstablishment
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof IPublicEstablishment
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof IPublicEstablishment
     */
    'logo': string;
    /**
     * 
     * @type {string}
     * @memberof IPublicEstablishment
     */
    'banner'?: string;
    /**
     * 
     * @type {EstablishmentStatus}
     * @memberof IPublicEstablishment
     */
    'status': EstablishmentStatus;
    /**
     * 
     * @type {string}
     * @memberof IPublicEstablishment
     */
    'openingHours'?: string;
    /**
     * 
     * @type {IAddress}
     * @memberof IPublicEstablishment
     */
    'address': IAddress;
    /**
     * 
     * @type {Array<PaymentMethod>}
     * @memberof IPublicEstablishment
     */
    'paymentMethods': Array<PaymentMethod>;
    /**
     * 
     * @type {string}
     * @memberof IPublicEstablishment
     */
    'description'?: string;
}



