/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ISelectedChoice } from './iselected-choice';

/**
 * 
 * @export
 * @interface ISelectedOptionGroup
 */
export interface ISelectedOptionGroup {
    /**
     * 
     * @type {string}
     * @memberof ISelectedOptionGroup
     */
    'name': string;
    /**
     * 
     * @type {Array<ISelectedChoice>}
     * @memberof ISelectedOptionGroup
     */
    'choices': Array<ISelectedChoice>;
}

