/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ITenantBranding } from './itenant-branding';

/**
 * 
 * @export
 * @interface ITenantConfig
 */
export interface ITenantConfig {
    /**
     * 
     * @type {string}
     * @memberof ITenantConfig
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ITenantConfig
     */
    'name': string;
    /**
     * 
     * @type {ITenantBranding}
     * @memberof ITenantConfig
     */
    'branding': ITenantBranding;
    /**
     * 
     * @type {string}
     * @memberof ITenantConfig
     */
    'identityPlatformTenantId': string;
}

