/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateTenantBodyBranding } from './create-tenant-body-branding';

/**
 * Make all properties in T optional
 * @export
 * @interface PartialCreateTenantBody
 */
export interface PartialCreateTenantBody {
    /**
     * 
     * @type {string}
     * @memberof PartialCreateTenantBody
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialCreateTenantBody
     */
    'slug'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PartialCreateTenantBody
     */
    'domains'?: Array<string>;
    /**
     * 
     * @type {CreateTenantBodyBranding}
     * @memberof PartialCreateTenantBody
     */
    'branding'?: CreateTenantBodyBranding;
    /**
     * 
     * @type {string}
     * @memberof PartialCreateTenantBody
     */
    'contactEmail'?: string;
}

