/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UpdateCustomerProfileBodyBillingInformation } from './update-customer-profile-body-billing-information';
// May contain unused imports in some cases
// @ts-ignore
import { UpdateCustomerProfileBodyDeliveryAddress } from './update-customer-profile-body-delivery-address';

/**
 * 
 * @export
 * @interface UpdateCustomerProfileBody
 */
export interface UpdateCustomerProfileBody {
    /**
     * 
     * @type {UpdateCustomerProfileBodyBillingInformation}
     * @memberof UpdateCustomerProfileBody
     */
    'billingInformation'?: UpdateCustomerProfileBodyBillingInformation;
    /**
     * 
     * @type {UpdateCustomerProfileBodyDeliveryAddress}
     * @memberof UpdateCustomerProfileBody
     */
    'deliveryAddress'?: UpdateCustomerProfileBodyDeliveryAddress;
}

