/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OptionGroupBody } from './option-group-body';

/**
 * 
 * @export
 * @interface UpdateProductBody
 */
export interface UpdateProductBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateProductBody
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductBody
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductBody
     */
    'category'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductBody
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductBody
     */
    'location'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductBody
     */
    'quantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductBody
     */
    'serialNumber'?: string;
    /**
     * 
     * @type {Array<OptionGroupBody>}
     * @memberof UpdateProductBody
     */
    'optionGroups'?: Array<OptionGroupBody>;
}

