/* tslint:disable */
/* eslint-disable */
/**
 * @mercashop/api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { GetEstablishment200Response } from '../models';
// @ts-ignore
import { GetEstablishments200Response } from '../models';
// @ts-ignore
import { UpdateEstablishmentStatusBody } from '../models';
/**
 * EstablishmentApi - axios parameter creator
 * @export
 */
export const EstablishmentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEstablishment: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getEstablishment', 'id', id)
            const localVarPath = `/api/establishments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEstablishments: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/establishments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateEstablishmentStatusBody} updateEstablishmentStatusBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStatus: async (updateEstablishmentStatusBody: UpdateEstablishmentStatusBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateEstablishmentStatusBody' is not null or undefined
            assertParamExists('updateStatus', 'updateEstablishmentStatusBody', updateEstablishmentStatusBody)
            const localVarPath = `/api/establishments/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateEstablishmentStatusBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EstablishmentApi - functional programming interface
 * @export
 */
export const EstablishmentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EstablishmentApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEstablishment(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetEstablishment200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEstablishment(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EstablishmentApi.getEstablishment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEstablishments(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetEstablishments200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEstablishments(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EstablishmentApi.getEstablishments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateEstablishmentStatusBody} updateEstablishmentStatusBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStatus(updateEstablishmentStatusBody: UpdateEstablishmentStatusBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetEstablishment200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateStatus(updateEstablishmentStatusBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EstablishmentApi.updateStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EstablishmentApi - factory interface
 * @export
 */
export const EstablishmentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EstablishmentApiFp(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEstablishment(id: string, options?: any): AxiosPromise<GetEstablishment200Response> {
            return localVarFp.getEstablishment(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEstablishments(options?: any): AxiosPromise<GetEstablishments200Response> {
            return localVarFp.getEstablishments(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateEstablishmentStatusBody} updateEstablishmentStatusBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStatus(updateEstablishmentStatusBody: UpdateEstablishmentStatusBody, options?: any): AxiosPromise<GetEstablishment200Response> {
            return localVarFp.updateStatus(updateEstablishmentStatusBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EstablishmentApi - object-oriented interface
 * @export
 * @class EstablishmentApi
 * @extends {BaseAPI}
 */
export class EstablishmentApi extends BaseAPI {
    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EstablishmentApi
     */
    public getEstablishment(id: string, options?: RawAxiosRequestConfig) {
        return EstablishmentApiFp(this.configuration).getEstablishment(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EstablishmentApi
     */
    public getEstablishments(options?: RawAxiosRequestConfig) {
        return EstablishmentApiFp(this.configuration).getEstablishments(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdateEstablishmentStatusBody} updateEstablishmentStatusBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EstablishmentApi
     */
    public updateStatus(updateEstablishmentStatusBody: UpdateEstablishmentStatusBody, options?: RawAxiosRequestConfig) {
        return EstablishmentApiFp(this.configuration).updateStatus(updateEstablishmentStatusBody, options).then((request) => request(this.axios, this.basePath));
    }
}

